default:
  navigation:
    - title: Inicio
      url: /
    - title: Piletas
      url: /t/construccion-de-piletas
    - title: Productos
      url: /productos-para-construir-tu-pileta
    - title: Quienes somos
      url: /quienes-somos
    - title: Preguntas frec.
      url: /preguntas-frecuentes
    - title: Contacto
      url: /contact-us

#  navigation:
#    - title: Piletas
#      subtitle: Categorías
#      url: /t/piletas
#      items:
#        - :title: Skirts
#          :url: /t/women/skirts
#        - :title: Dresses
#          :url: /t/women/dresses
#        - :title: Shirts and Blouses
#          :url: /t/women/shirts-and-blouses
#        - :title: Sweaters
#          :url: /t/women/sweaters
#        - :title: Tops and T-shirts
#          :url: /t/women/tops-and-t-shirts
#        - :title: Jackets and Coats
#          :url: /t/women/jackets-and-coats
#      promo_banners:
#        - subtitle: New collection
#          title: Summer 2019
#          url: /t/new-collection/summer-2019
#          image: 'meganav/promo_banner_left-first-category.jpg'
#        - subtitle: Special Offers
#          title: Get up to 30% off
#          url: /t/special-offers/30-off
#          image: 'meganav/promo_banner_right-first-category.jpg'
#    - title: Productos y servicios
#      subtitle: Categorías
#      url: /t/productos-y-servicios
#      items:
#        - :title: Piletas
#          :url: /t/men/shirts
#        - :title: Spas
#          :url: /t/men/t-shirts
#        - :title: Equipamiento de piletas
#          :url: /t/men/sweaters
#        - :title: Accesorios para piletas
#          :url: /t/men/jackets-and-coats
#        - :title: Decoración
#          :url: /t/men/t-shirts
#        - :title: Locetas atérmicas
#          :url: /t/men/t-shirts
#      items2:
#        - :title: Revestimientos para piletas
#          :url: /t/men/t-shirts
#        - :title: Cubiertas
#          :url: /t/men/t-shirts
#        - :title: decks
#          :url: /t/men/t-shirts
#        - :title: Hidromasajes
#          :url: /t/men/t-shirts
#        - :title: Guardas
#          :url: /t/men/t-shirts
#      items3:
#        - :title: Climatización
#          :url: /t/men/t-shirts
#        - :title: Iluminación
#          :url: /t/men/t-shirts
#        - :title: Pinturas para piletas
#          :url: /t/men/t-shirts
#        - :title: Cascadas
#          :url: /t/men/t-shirts
#        - :title: Fuentes
#          :url: /t/men/t-shirts
#        - :title: Desborde Finlandés
#          :url: /t/men/t-shirts
#    - title: Quienes somos
#      url: /quienes-somos
#    - title: Contacto
#      url: /contacto
#    - title: Blog
#      url: /blog